CREATE TABLE rooms_photos (
    id_room_photo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_room BIGINT NOT NULL,
    image_url VARCHAR(255) NOT NULL,
    alt_text VARCHAR(255),
    display_order SMALLINT NOT NULL DEFAULT 0,

    CONSTRAINT fk_room_photo_room
        FOREIGN KEY (id_room)
        REFERENCES rooms (id_room)
        ON DELETE CASCADE,

    CONSTRAINT chk_room_photo_display_order
        CHECK (display_order >= 0)
);
