CREATE TABLE rooms_unavailabilities (
    id_room_unavailability INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_room INTEGER NOT NULL,
    start_datetime TIMESTAMP NOT NULL,
    end_datetime TIMESTAMP NOT NULL,
    reason VARCHAR(255),
    unavailability_status VARCHAR(30) NOT NULL,

    CONSTRAINT fk_room_unavailability_room
        FOREIGN KEY (id_room)
        REFERENCES rooms (id_room)
        ON DELETE CASCADE,

    CONSTRAINT chk_room_unavailability_dates
        CHECK (end_datetime > start_datetime)
);