CREATE TABLE reservations (
    id_reservation INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_user INTEGER NOT NULL,
    id_room INTEGER NOT NULL,
    start_datetime TIMESTAMP NOT NULL,
    end_datetime TIMESTAMP NOT NULL,
    reservation_status VARCHAR(30) NOT NULL,
    total_amount NUMERIC(10, 2) NOT NULL,
    payment_method VARCHAR(30),
    is_paid BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_reservation_client
        FOREIGN KEY (id_user)
        REFERENCES client (id_user)
        ON DELETE CASCADE,

    CONSTRAINT fk_reservation_room
        FOREIGN KEY (id_room)
        REFERENCES room (id_room)
        ON DELETE RESTRICT,

    CONSTRAINT chk_reservation_dates
        CHECK (end_datetime > start_datetime),

    CONSTRAINT chk_reservation_total_amount
        CHECK (total_amount >= 0)
);