CREATE TABLE rooms_reviews (
    id_review BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_reservation BIGINT NOT NULL,
    rating SMALLINT NOT NULL,
    comment TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_anonymous BOOLEAN NOT NULL DEFAULT FALSE,
    is_verified BOOLEAN NOT NULL DEFAULT FALSE,
    updated_at TIMESTAMP,
    response_content TEXT,
    response_date TIMESTAMP,

    CONSTRAINT fk_room_review_reservation
        FOREIGN KEY (id_reservation)
        REFERENCES reservations (id_reservation)
        ON DELETE CASCADE,

    CONSTRAINT uq_room_review_reservation
        UNIQUE (id_reservation),

    CONSTRAINT chk_room_review_rating
        CHECK (rating BETWEEN 1 AND 5)
);
