CREATE TABLE notifications (
    id_notification BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_user BIGINT NOT NULL,
    notification_type VARCHAR(80) NOT NULL,
    content TEXT NOT NULL,
    sent_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT fk_notification_user
        FOREIGN KEY (id_user)
        REFERENCES users (id_user)
        ON DELETE CASCADE
);
