CREATE TABLE hotel_feedbacks (
    id_feedback BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_user BIGINT NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_displayed BOOLEAN NOT NULL DEFAULT FALSE,
    response_date TIMESTAMP,
    response_content TEXT,

    CONSTRAINT fk_hotel_feedback_user
        FOREIGN KEY (id_user)
        REFERENCES users (id_user)
        ON DELETE CASCADE
);
