CREATE TABLE leave_requests (
    id_leave_request INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_employee_requester INTEGER NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    reason TEXT,
    leave_type VARCHAR(30) NOT NULL,
    request_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    current_status VARCHAR(30) NOT NULL,

    CONSTRAINT fk_leave_request_employee_requester
        FOREIGN KEY (id_employee_requester)
        REFERENCES employees (id_user)
        ON DELETE CASCADE,

    CONSTRAINT chk_leave_request_dates
        CHECK (end_date >= start_date)
);