CREATE TABLE leave_requests_validation (
    id_leave_request_validation INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_leave_request INTEGER NOT NULL,
    id_employee_validator INTEGER NOT NULL,
    step_order SMALLINT NOT NULL,
    decision VARCHAR(30) NOT NULL,
    decision_date TIMESTAMP,
    comment TEXT,

    CONSTRAINT fk_leave_request_validation_request
        FOREIGN KEY (id_leave_request)
        REFERENCES leave_requests (id_leave_request)
        ON DELETE CASCADE,

    CONSTRAINT fk_leave_request_validation_employee_validator
        FOREIGN KEY (id_employee_validator)
        REFERENCES employees (id_user)
        ON DELETE RESTRICT,

    CONSTRAINT uq_leave_request_validation_step
        UNIQUE (id_leave_request, step_order),

    CONSTRAINT chk_leave_request_validation_step_order
        CHECK (step_order > 0)
);