CREATE TABLE monthly_schedules (
    id_monthly_schedule INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_month SMALLINT NOT NULL,
    schedule_year SMALLINT NOT NULL,
    creation_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    schedule_status VARCHAR(30) NOT NULL,
    publication_date TIMESTAMP,

    CONSTRAINT uq_monthly_schedule_month_year
        UNIQUE (schedule_month, schedule_year),

    CONSTRAINT chk_monthly_schedule_month
        CHECK (schedule_month BETWEEN 1 AND 12),

    CONSTRAINT chk_monthly_schedule_year
        CHECK (schedule_year >= 2000)
);