--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: client; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.client (
    user_id bigint NOT NULL,
    fidelity_point integer DEFAULT 0 NOT NULL
);


--
-- Name: employee; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.employee (
    user_id bigint NOT NULL,
    status character varying(255),
    team character varying(255),
    CONSTRAINT employee_status_check CHECK (((status)::text = ANY ((ARRAY['ADDED'::character varying, 'REMOVED'::character varying])::text[])))
);


--
-- Name: employee_vacation; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.employee_vacation (
    id bigint NOT NULL,
    is_accepted boolean,
    vacation_end date,
    vacation_start date,
    employee_id bigint
);


--
-- Name: employee_vacation_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.employee_vacation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employee_vacation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: employee_workday; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.employee_workday (
    weekday integer NOT NULL,
    work_date date NOT NULL,
    clock_in time(6) without time zone,
    clock_out time(6) without time zone,
    idle_time numeric(21,0),
    planned_break_minutes integer,
    planned_end_time time(6) without time zone,
    planned_start_time time(6) without time zone,
    employee_id bigint NOT NULL
);


--
-- Name: feedback; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.feedback (
    id bigint NOT NULL,
    answer character varying(255),
    content character varying(255) NOT NULL,
    date timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: feedback_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.feedback_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: leave_requests; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.leave_requests (
    id bigint NOT NULL,
    approved_at timestamp(6) without time zone,
    approved_by character varying(100),
    created_at timestamp(6) without time zone NOT NULL,
    employee_id bigint NOT NULL,
    end_date date NOT NULL,
    reason character varying(500),
    rejected_at timestamp(6) without time zone,
    rejected_by character varying(100),
    rejection_reason character varying(500),
    start_date date NOT NULL,
    status character varying(20) NOT NULL,
    type character varying(50) NOT NULL,
    updated_at timestamp(6) without time zone,
    CONSTRAINT leave_requests_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying, 'CANCELLED'::character varying, 'WITHDRAWN'::character varying])::text[]))),
    CONSTRAINT leave_requests_type_check CHECK (((type)::text = ANY ((ARRAY['VACATION'::character varying, 'SICK'::character varying, 'PERSONAL'::character varying, 'MATERNITY'::character varying, 'PATERNITY'::character varying, 'BEREAVEMENT'::character varying, 'EMERGENCY'::character varying, 'STUDY'::character varying, 'UNPAID'::character varying])::text[])))
);


--
-- Name: leave_requests_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.leave_requests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.leave_requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reviews; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reviews (
    id bigint NOT NULL,
    author_id bigint NOT NULL,
    comment character varying(1000),
    created_at timestamp(6) without time zone NOT NULL,
    helpful_count integer,
    is_anonymous boolean NOT NULL,
    is_verified boolean NOT NULL,
    rating integer NOT NULL,
    reported_count integer,
    review_date date NOT NULL,
    room_id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    verified_at timestamp(6) without time zone,
    verified_by character varying(100)
);


--
-- Name: reviews_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.reviews ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reviews_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: room; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.room (
    id bigint NOT NULL,
    capacity integer NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by character varying(100),
    description character varying(1000),
    floor_number integer,
    has_air_conditioning boolean,
    has_projector boolean,
    has_video_conference boolean,
    has_whiteboard boolean,
    image_url character varying(500),
    last_maintenance_date timestamp(6) without time zone,
    name character varying(100),
    next_maintenance_date timestamp(6) without time zone,
    number character varying(255) NOT NULL,
    price double precision,
    status character varying(100) NOT NULL,
    type character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    CONSTRAINT room_status_check CHECK (((status)::text = ANY ((ARRAY['AVAILABLE'::character varying, 'OCCUPIED'::character varying, 'MAINTENANCE'::character varying, 'OUT_OF_ORDER'::character varying, 'RESERVED'::character varying, 'CLEANING'::character varying])::text[]))),
    CONSTRAINT room_type_check CHECK (((type)::text = ANY ((ARRAY['STANDARD'::character varying, 'SUPERIOR'::character varying, 'DELUXE'::character varying, 'JUNIOR_SUITE'::character varying, 'SUITE'::character varying, 'PRESIDENTIAL_SUITE'::character varying, 'FAMILY_ROOM'::character varying, 'TWIN'::character varying, 'DOUBLE'::character varying, 'SINGLE'::character varying, 'PENTHOUSE'::character varying, 'CONFERENCE'::character varying, 'MEETING'::character varying, 'OFFICE'::character varying, 'TRAINING'::character varying, 'BOARDROOM'::character varying, 'HUDDLE'::character varying, 'PHONE_BOOTH'::character varying, 'LOUNGE'::character varying, 'COLLABORATION'::character varying, 'PRESENTATION'::character varying, 'ROOM'::character varying, 'EVENT'::character varying])::text[])))
);


--
-- Name: room_amenities; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.room_amenities (
    room_id bigint NOT NULL,
    amenity character varying(255)
);


--
-- Name: room_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.room ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.room_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."user" (
    id bigint NOT NULL,
    email character varying(150) NOT NULL,
    first_name character varying(100) NOT NULL,
    last_name character varying(100) NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    CONSTRAINT user_role_check CHECK (((role)::text = ANY ((ARRAY['CLIENT'::character varying, 'EMPLOYEE'::character varying, 'ADMIN'::character varying])::text[])))
);


--
-- Name: user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: user_reservation; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_reservation (
    payed boolean NOT NULL,
    reservation_date_end date NOT NULL,
    reservation_date_start date NOT NULL,
    room_id bigint NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: client client_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.client
    ADD CONSTRAINT client_pkey PRIMARY KEY (user_id);


--
-- Name: employee employee_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employee
    ADD CONSTRAINT employee_pkey PRIMARY KEY (user_id);


--
-- Name: employee_vacation employee_vacation_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employee_vacation
    ADD CONSTRAINT employee_vacation_pkey PRIMARY KEY (id);


--
-- Name: employee_workday employee_workday_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employee_workday
    ADD CONSTRAINT employee_workday_pkey PRIMARY KEY (employee_id, weekday, work_date);


--
-- Name: feedback feedback_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.feedback
    ADD CONSTRAINT feedback_pkey PRIMARY KEY (id);


--
-- Name: leave_requests leave_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.leave_requests
    ADD CONSTRAINT leave_requests_pkey PRIMARY KEY (id);


--
-- Name: reviews reviews_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT reviews_pkey PRIMARY KEY (id);


--
-- Name: room room_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.room
    ADD CONSTRAINT room_pkey PRIMARY KEY (id);


--
-- Name: room uk36mkgyjf7t5hsxx4vtp89i9ey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.room
    ADD CONSTRAINT uk36mkgyjf7t5hsxx4vtp89i9ey UNIQUE (number);


--
-- Name: user ukhl4ga9r00rh51mdaf20hmnslt; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT ukhl4ga9r00rh51mdaf20hmnslt UNIQUE (email);


--
-- Name: reviews ukq7sslxpfv9aea91d78o0mf7n1; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT ukq7sslxpfv9aea91d78o0mf7n1 UNIQUE (room_id, author_id);


--
-- Name: user user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_pkey PRIMARY KEY (id);


--
-- Name: user_reservation user_reservation_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_reservation
    ADD CONSTRAINT user_reservation_pkey PRIMARY KEY (room_id, user_id);


--
-- Name: user_reservation fk5a0ytx9pbivcqndllaitwpoq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_reservation
    ADD CONSTRAINT fk5a0ytx9pbivcqndllaitwpoq FOREIGN KEY (user_id) REFERENCES public."user"(id);


--
-- Name: room_amenities fk5hjyttdqm1931pct5kaix8d6x; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.room_amenities
    ADD CONSTRAINT fk5hjyttdqm1931pct5kaix8d6x FOREIGN KEY (room_id) REFERENCES public.room(id);


--
-- Name: feedback fk6xn6ah744nvjpnblisld6i3o1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.feedback
    ADD CONSTRAINT fk6xn6ah744nvjpnblisld6i3o1 FOREIGN KEY (user_id) REFERENCES public."user"(id);


--
-- Name: user_reservation fkb7y84ydoboab2ms53p9d33tx6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_reservation
    ADD CONSTRAINT fkb7y84ydoboab2ms53p9d33tx6 FOREIGN KEY (room_id) REFERENCES public.room(id);


--
-- Name: employee_workday fke4sh18v97k415qjinmcqtb6ma; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employee_workday
    ADD CONSTRAINT fke4sh18v97k415qjinmcqtb6ma FOREIGN KEY (employee_id) REFERENCES public.employee(user_id);


--
-- Name: employee fkf5lkvqkqs89qdqluo4couya15; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employee
    ADD CONSTRAINT fkf5lkvqkqs89qdqluo4couya15 FOREIGN KEY (user_id) REFERENCES public."user"(id);


--
-- Name: employee_vacation fkitvs32bcvun656id34i33qo6v; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employee_vacation
    ADD CONSTRAINT fkitvs32bcvun656id34i33qo6v FOREIGN KEY (employee_id) REFERENCES public.employee(user_id);


--
-- Name: client fkmi4tlsbdbmn0myf9cejh82chh; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.client
    ADD CONSTRAINT fkmi4tlsbdbmn0myf9cejh82chh FOREIGN KEY (user_id) REFERENCES public."user"(id);


--
-- PostgreSQL database dump complete
--

