CREATE TABLE work_shifts (
    id_work_shift INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_user INTEGER NOT NULL,
    id_monthly_schedule INTEGER NOT NULL,
    work_date DATE NOT NULL,
    planned_start_time TIME NOT NULL,
    planned_end_time TIME NOT NULL,
    planned_break_start TIME,
    planned_break_end TIME,
    shift_type VARCHAR(50) NOT NULL,
    service VARCHAR(100),
    shift_status VARCHAR(30) NOT NULL,

    CONSTRAINT fk_work_shift_employee
        FOREIGN KEY (id_user)
        REFERENCES employee (id_user)
        ON DELETE CASCADE,

    CONSTRAINT fk_work_shift_monthly_schedule
        FOREIGN KEY (id_monthly_schedule)
        REFERENCES monthly_schedule (id_monthly_schedule)
        ON DELETE CASCADE,

    CONSTRAINT chk_work_shift_break
        CHECK (
            planned_break_start IS NULL
            OR planned_break_end IS NULL
            OR planned_break_end > planned_break_start
        )
);