CREATE TABLE employees_times_entry (
    id_time_entry INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_work_shift INTEGER NOT NULL,
    actual_arrival_time TIMESTAMP,
    actual_departure_time TIMESTAMP,
    actual_break_duration INTEGER NOT NULL DEFAULT 0,
    attendance_status VARCHAR(30) NOT NULL,

    CONSTRAINT fk_employee_time_entry_work_shift
        FOREIGN KEY (id_work_shift)
        REFERENCES work_shift (id_work_shift)
        ON DELETE CASCADE,

    CONSTRAINT chk_employee_time_entry_times
        CHECK (
            actual_arrival_time IS NULL
            OR actual_departure_time IS NULL
            OR actual_departure_time >= actual_arrival_time
        ),

    CONSTRAINT chk_employee_time_entry_break_duration
        CHECK (actual_break_duration >= 0)
);