ALTER TABLE rooms
    ADD COLUMN has_projector BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN has_whiteboard BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN has_video_conference BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN has_air_conditioning BOOLEAN NOT NULL DEFAULT TRUE;
