CREATE TABLE rooms (
    id_room BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_number VARCHAR(20) NOT NULL UNIQUE,
    room_type VARCHAR(50) NOT NULL,
    capacity SMALLINT NOT NULL,
    base_price NUMERIC(10, 2) NOT NULL,
    room_status VARCHAR(30) NOT NULL,
    description TEXT,

    CONSTRAINT chk_room_capacity
        CHECK (capacity > 0),

    CONSTRAINT chk_room_base_price
        CHECK (base_price >= 0)
);
