server:
  port: 8080
  error:
    include-stacktrace: always
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:postgresql://100.127.131.70:5432/overlookhoteldb
    username: dev
    password: _GB7rG-@*d649Pab
    #     url: jdbc:postgresql://localhost:5432/postgres
    #     username: postgres
    #     password: Admin123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    spring.jpa.hibernate.ddl-auto: update
    spring.jpa.show-sql: true
    spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  thymeleaf:
    cache: false

  devtools:
    restart:
      enabled: true

  security:
    user:
      name: admin
      password: admin

logging:
  level:
    '[org.springframework.security]': DEBUG
    '[org.hibernate.SQL]': DEBUG
    '[org.hibernate.type.descriptor.sql.BasicBinder]': TRACE
    '[org.springframework.web]': DEBUG
    '[master.master]': DEBUG
    root: INFO
