server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/OverlookHostel
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  thymeleaf:
    cache: false

  devtools:
    restart:
      enabled: true

  security:
    user:
      name: admin
      password: admin

logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
